# Generated by Django 4.0.6 on 2022-07-27 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Author',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('Author_name', models.CharField(max_length=50)),
        #         ('Blogpost_name', models.CharField(max_length=50)),
        #         ('Post_date', models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 35, 12, 133658, tzinfo=utc), verbose_name='set date')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('User_name', models.CharField(max_length=50)),
        #         ('User_pwd', models.CharField(max_length=50)),
        #         ('blog_title', models.CharField(max_length=50)),
        #         ('Post_date', models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 35, 12, 134859, tzinfo=utc), verbose_name='set date')),
        #         ('Author_name', models.CharField(max_length=50)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Comment',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('Blogpost_name', models.CharField(max_length=50)),
        #         ('Content', models.CharField(max_length=50)),
        #         ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.author')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Blog_Post',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('Blogpost_name', models.CharField(max_length=50)),
        #         ('Author_name', models.CharField(max_length=50)),
        #         ('Post_date', models.DateTimeField(default=datetime.datetime(2022, 7, 27, 11, 35, 12, 134150, tzinfo=utc), verbose_name='set date')),
        #         ('Content', models.CharField(max_length=100)),
        #         ('Blogpost_comment', models.CharField(max_length=100, null=True)),
        #         ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.author')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Admin',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('Admin_pwd', models.CharField(max_length=50)),
        #         ('Blogpost_comment', models.CharField(max_length=100)),
        #         ('Author_name', models.CharField(max_length=50)),
        #         ('Blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.blog_post')),
        #     ],
        # ),
    ]
