# Generated by Django 4.0.6 on 2022-07-28 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='admin',
        #     name='Blogpost',
        # ),
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='Author',
        # ),
        # migrations.DeleteModel(
        #     name='User',
        # ),
        # migrations.AlterField(
        #     model_name='author',
        #     name='Post_date',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 5, 59, 4, 472640, tzinfo=utc), verbose_name='set date'),
        # ),
        # migrations.AlterField(
        #     model_name='blog_post',
        #     name='Post_date',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 5, 59, 4, 473137, tzinfo=utc), verbose_name='set date'),
        # ),
        # migrations.DeleteModel(
        #     name='Admin',
        # ),
        # migrations.DeleteModel(
        #     name='Comment',
        # ),
    ]
