# Generated by Django 4.0.6 on 2022-07-28 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_admin_blogpost_remove_comment_author_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='User',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('User_name', models.CharField(max_length=50)),
        #         ('User_mail', models.CharField(max_length=50)),
        #         ('User_pwd', models.CharField(max_length=50)),
        #         ('User_pno', models.IntegerField()),
        #     ],
        # ),
        # migrations.RemoveField(
        #     model_name='blog_post',
        #     name='Author',
        # ),
        # migrations.RemoveField(
        #     model_name='blog_post',
        #     name='Author_name',
        # ),
        # migrations.RemoveField(
        #     model_name='blog_post',
        #     name='Blogpost_comment',
        # ),
        # migrations.AlterField(
        #     model_name='blog_post',
        #     name='Post_date',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 9, 56, 34, 260511, tzinfo=utc), verbose_name='date created'),
        # ),
        # migrations.DeleteModel(
        #     name='Author',
        # ),
        # migrations.AddField(
        #     model_name='blog_post',
        #     name='User',
        #     field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='members.user'),
        #     preserve_default=False,
        # ),
    ]
