# Generated by Django 4.0.6 on 2022-07-28 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_remove_blog_post_author_and_more'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='blog_post',
        #     name='Post_date',
        #     field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 9, 57, 38, 775162, tzinfo=utc), verbose_name='date created'),
        # ),
    ]
