# Generated by Django 4.0.6 on 2022-07-28 10:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=50)),
                ('User_mail', models.CharField(max_length=50)),
                ('User_pwd', models.CharField(max_length=50)),
                ('User_pno', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blogpost_name', models.CharField(max_length=50)),
                ('Post_date', models.DateTimeField(default=datetime.datetime(2022, 7, 28, 10, 5, 41, 623235, tzinfo=utc), verbose_name='date created')),
                ('Content', models.CharField(max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.user')),
            ],
        ),
    ]
